# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

environments: &environments
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.10

version: 2
jobs:
  build:
    <<: *environments

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm i -g typescript
      
      - run: npm i
      
      - run: node node_modules/tslint/bin/tslint --project tsconfig.json
      
      - run: tsc

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      -  persist_to_workspace:
            root: ./
            paths:
              - ./
  test:
    <<: *environments
    steps:
      - attach_workspace:
          at: ./
      - run: 
          command: npm test -- --runInBand --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
    